# Generated by Django 4.0.2 on 2022-12-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cart_item",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_item",
                to="market.cart",
            ),
        ),
    ]
