# Generated by Django 4.0.2 on 2022-12-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_rename_cart_item_cartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.FloatField(default=0, null=True),
        ),
    ]
