# Generated by Django 4.0.2 on 2022-12-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_cart_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.FloatField(default=0),
        ),
    ]
