# Generated by Django 4.1.4 on 2023-01-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_discount",
            field=models.FloatField(default=0, null=True),
        ),
    ]
