# Generated by Django 3.1.2 on 2020-12-05 01:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
