# Generated by Django 3.1.2 on 2020-12-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
