# Generated by Django 3.1.2 on 2020-12-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_auto_20201204_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
