# Generated by Django 3.1.2 on 2020-12-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_auto_20201204_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
