# Generated by Django 4.0.1 on 2022-01-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0005_alter_writer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.FileField(upload_to='images/writer'),
        ),
    ]
