# Generated by Django 4.0.2 on 2022-02-10 23:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0006_alter_writer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
