# Generated by Django 4.0.2 on 2022-12-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
