# Generated by Django 4.0.1 on 2022-01-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_banner_id_alter_contactmessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(upload_to='images/banner'),
        ),
    ]
