# Generated by Django 5.0.1 on 2025-12-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("keywords", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.FileField(null=True, upload_to="images/capa")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.IntegerField()),
                ("specification", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("is_publish", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "new"),
                            ("DISCOUNTED", "discounted"),
                            ("REGULAR", "regular"),
                            ("SOLD_OUT", "sold_out"),
                            ("ARCHIVED", "archived"),
                            ("PREORDER", "preorder"),
                        ],
                        default="NEW",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "books",
            },
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("image", models.FileField(null=True, upload_to="images/writer")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "writers",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("rate", models.IntegerField(default=1)),
                ("ip", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("APPROVED", "approved"),
                            ("REJECTED", "rejected"),
                        ],
                        default="PENDING",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="book.book",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="genre_origin",
                        to="book.genre",
                    ),
                ),
            ],
            options={
                "db_table": "genres",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="book.genre"
            ),
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("image", models.FileField(blank=True, upload_to="images/books")),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="book.book",
                    ),
                ),
            ],
            options={
                "db_table": "book_images",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="book.writer",
            ),
        ),
    ]
