# Generated by Django 5.0.1 on 2025-12-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
