# Generated by Django 5.0.1 on 2025-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
