# Generated by Django 4.0.1 on 2022-01-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_id_alter_comment_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='images/capa'),
        ),
    ]
