# Generated by Django 5.0.1 on 2025-12-30 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_genre_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="is_publish",
        ),
        migrations.RemoveField(
            model_name="book",
            name="keywords",
        ),
    ]
