# Generated by Django 3.1.2 on 2020-12-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
