# Generated by Django 4.0.2 on 2022-12-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_genre_alter_book_image_alter_book_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="publication_date",
        ),
    ]
