# Generated by Django 3.1.2 on 2020-12-08 21:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20201205_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
