# Generated by Django 3.1.2 on 2020-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
