# Generated by Django 3.1.2 on 2020-12-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_address',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
