# Generated by Django 3.1.2 on 2020-12-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_number_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number_address',
        ),
    ]
