# Generated by Django 5.0.1 on 2025-12-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcart",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_CART", "in_cart"),
                    ("REMOVED", "removed"),
                    ("BOUGTH", "bought"),
                ],
                default="IN_CART",
                max_length=30,
            ),
        ),
    ]
